### ISSUE TITLE
Secure App Code

### ISSUE THREAD

**Issue by sivasaiojam** [ActivityCounter/StrandHoggAttacks#1]
Hey @ActivityCounter ,  
      You created the PoC for the attacker app (StrandHogg 2.0) , but where is the code of the app to be attacked (Secure App ). Could you please share PoC of Secure App for the vulnerability StrandHogg 2.0 ?

**Comment by ActivityCounter** [comment]
Hi @sivasaiojam ,
due to legal reasons, we're not allowed to share the source code of the ActivityCounter app (you refer to it as Secure App). However, you could attack any other android app (by replacing victimPackageName and victimActivity), given that certain defense strategies are not in place.
If you are interested in our detection technique, you could refer to the ACM WiSec '21 paper "RIP StrandHogg: A Practical Detection Method on Android" for a detailed implementation description.
